param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

$moduleDir = Join-Path $Root "reframework\autorun\re9mp"
$outFile = Join-Path $Root "reframework\autorun\re9mp.lua"

$chunks = @(
    "core\legacy_00_state_and_snapshots.lua",
    "tracing\legacy_10_trace_hooks.lua",
    "tracing\legacy_20_diagnostics_helpers.lua",
    "tracing\legacy_21_character_and_visual_probes.lua",
    "spawn\legacy_30_context_and_controller_helpers.lua",
    "spawn\legacy_40_load_phase_injection.lua",
    "spawn\legacy_50_visual_foundation.lua",
    "spawn\legacy_51_mesh_copy_and_registration.lua",
    "spawn\legacy_52_lit_control_clone.lua",
    "tracing\legacy_60_ownership_recipe.lua",
    "archive\legacy_70_archived_prefab_and_spawn_probes.lua",
    "runtime\legacy_80_commands_ui_callbacks.lua"
)

$missing = @()
foreach ($chunk in $chunks) {
    $path = Join-Path $moduleDir $chunk
    if (-not (Test-Path -LiteralPath $path)) {
        $missing += $path
    }
}

if ($missing.Count -gt 0) {
    throw "Missing Lua chunk(s): $($missing -join ', ')"
}

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add("-- RE9 Multiplayer MVP runtime bundle.")
$parts.Add("-- Generated by scripts/build_lua_bundle.ps1 from reframework/autorun/re9mp/.")
$parts.Add("-- REFramework ScriptRunner cannot reliably dofile sibling modules from autorun.")
$parts.Add("")

foreach ($chunk in $chunks) {
    $path = Join-Path $moduleDir $chunk
    $normalized = $chunk.Replace("\", "/")
    $parts.Add("")
    $parts.Add("-- chunk: $normalized")
    $parts.Add((Get-Content -LiteralPath $path -Raw).TrimEnd("`r", "`n"))
    $parts.Add("")
}

$content = ($parts -join "`n").TrimEnd("`r", "`n") + "`n"
[System.IO.File]::WriteAllText($outFile, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "Built Lua bundle: $outFile"
